#!/bin/bash

set -eo pipefail

########################################################
# This script starts up the build process.
########################################################

echo "Begin build for $TERMINUS_ENV. Pantheon test environment is $TERMINUS_SITE.$TERMINUS_ENV"

# Report installed version of Terminus
terminus --version
