#!/bin/bash

set -eo pipefail

########################################################
# Deploy code to the development environment
########################################################

# Permform a git merge and push to dev
terminus -n env:wake "$TERMINUS_SITE.dev"
terminus build:env:create -n "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes

# Run updatedb to ensure that the cloned database is updated for the new code.
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y

# If any config has been updated perform a config import in the dev environment
# to test that everything is working as expected.
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- cim -y

# If any modules, or theme files have been moved around or reorganized, in order to avoid
# "The website encountered an unexpected error. Please try again later." error on First Visit
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" cr
